# -*- coding: utf-8 -*-
"""P16732.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hyWrvPs9PHLLtGogbiJEwwjH8ojFDc5f
"""

from mimetypes import init
from RPSLS_player import RPSLS_player

class P16732(RPSLS_player):
  def __init__(self):
    pass

  def shoot(self):
    shootlist = ["rock", "paper", "scissors", "lizard", "spock"]
    import random
    return random.choice(shootlist)
  
  def update(self, result: str, competitor_shot: str):
    pass
